# Generated by Django 4.1.7 on 2023-03-11 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 19, 56, 50, 514589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 19, 56, 50, 514899, tzinfo=datetime.timezone.utc)),
        ),
    ]
