# Generated by Django 4.1.7 on 2023-03-11 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_myuser_created_date_alter_myuser_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 19, 58, 19, 865829, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 11, 19, 58, 19, 866200, tzinfo=datetime.timezone.utc)),
        ),
    ]
